### ISSUE TITLE
MVP Roadmap

### ISSUE THREAD

**Issue by samidalouche** [samidalouche/simplets#1]
# Correctness

## API definition
 - [ ]  Is `text/plain` OK as the `Content-Type`?
- [ ] Review usage of `java.time` API, UTC handling, etc (first time I played with java8 time API, so I may have done some newbie mistakes)

## Idempotence
> - Could partners submit the same data several times? (retries, etc)

- [ ] If partners could submit the same data several times, special care would be needed to make the projections idempotent. Use timestamp as key? Use a different identifier? Do the partners always send their data ordered by timestamp? 

## Persistence

- [ ] Make the Event Log durable and thread-safe. 

# Documentation

- [ ] HTTP API documentation optimized for whoever is going to use it

# Productivity Engineering

- [ ] Continuous Integration & dockerization
- [ ] Proper release / Changelog / deployment mechanism
- [ ] Missing tests
  - [ ] End to end tests
  - [ ] `AtLeastOnceStreamConsumer` : Probably need unit tests simulating the failures/retries, and some real-life integrated tests
  - [ ] `AggregationProcess` (or the underlying flow at least) should be tested with infinite streams to make sure things are OK in the real life
  - [ ] `Offset`
  - [ ] `Futures.traverseSequentially`
- [ ] Exporting tools (debugging, manual QA,...)

# Production Engineering

## Deployment
- [ ] Health Checks
- [ ] Technical Monitoring / Timeseries / Alerts...
- [ ] Docker
- [ ] Persistence strategy
- [ ] Backups
- [ ] Run the projections as part of a different service than the REST API
- [ ] Make the port, address, etc configurable

## Performance and Scalability

> - What kind of traffic (POST/GET) do we expect in production?
> - What is the maximum number of distinct users appearing in a given aggregation window?

- [ ] Do not snapshot on each event. Batch the input
- [ ] Is it needed to back the last hour data by an in memory store for faster access? Or simply the snapshot?
- [ ] Will scalability ever be needed for the main event log worker? What could be the keys to shard on?
- [ ] Bound the maximum size of the in-memory states (could grow indefinitely because of distinct users count).
- [ ] Queries freshness. Depending on the constraints, can we make the queries more efficient by caching the previous results longer and not regenerating the snapshots with every new event?
- [ ] Blocking calls (`memory-infra`)
  - [ ] `InMemoryStream`
  - [ ] `InMemorySnapshotStore

## Security

- [ ] Authenticate/Authorize the endpoints
- [ ] Record additional contextual information (IP address, etc)

# Business support

- [ ] Any data the business needs to evaluate the feature, ...
